Feature/sph0645 mems mic
CodeForAfrica/sensors.AFRICA-AQ-sensors-software pull request #34
Opened 2020-05-15 14:38 UTC by MCLEANS

## Description

1. Added functionality to read audio data from SPH0645 Mic.
2. Convert raw audio data to dB.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-05-17 10:25 UTC, chegejames requested changes
@MCLEANS please look at the comments for the changes requested.

2020-05-17 10:25 UTC, chegejames commented on airrohr-firmware/SPH0645.h
> +i2s_set_rate(uint32_t rate)
@MCLEANS let's stick to one styling guide.

2020-05-17 10:25 UTC, chegejames commented on airrohr-firmware/ext_def.h
> +#define SPHO645_READ  0
@MCLEANS I believe we want this to default to true

2020-05-17 10:25 UTC, chegejames commented on airrohr-firmware/SPH0645.h
> +void ICACHE_RAM_ATTR
@MCLEANS let's please stick to one styling guide.

2020-05-17 10:25 UTC, chegejames commented on airrohr-firmware/ext_def.h
> +#define SPHO645_READ  0
@MCLEANS also missing is are the pin assignments

2020-05-18 05:47 UTC, MCLEANS commented
@chegejames I have made the changes as requested.

2020-05-19 06:05 UTC, merged