Feature/enable webserver
CodeForAfrica/sensors.AFRICA-AQ-sensors-software pull request #50
Opened 2020-08-03 11:59 UTC by MCLEANS

## Description

1. Enabled web-server to function offline.
2. Disabled web-server redirects.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

2020-08-05 08:10 UTC, chegejames requested changes

2020-08-05 08:10 UTC, chegejames commented on airrohr-firmware/airrohr-firmware.ino
> +			"<tr><th> " INTL_PARAMETER "</th><th>" INTL_VALUE "</th></tr>");
@MCLEANS please restore this extra space.

2020-08-05 08:10 UTC, chegejames commented on airrohr-firmware/airrohr-firmware.ino
> +	add_table_row_from_value(page_content, F("NTP Sync"), String(sntp_time_set));
@MCLEANS same here. Please revert to original spacing.

2020-08-05 08:10 UTC, chegejames commented on airrohr-firmware/airrohr-firmware.ino
> +
@MCLEANS please remove the extra new line.

2020-08-05 08:10 UTC, chegejames commented on airrohr-firmware/airrohr-firmware.ino
> +		sendHttpRedirect();
@MCLEANS please remove this trailing extra space.

2020-08-05 09:19 UTC, MCLEANS commented
@chegejames  I have made the requested changes.

2020-08-07 07:30 UTC, chegejames approved these changes

2020-08-07 07:31 UTC, merged